### ISSUE TITLE
Crash setting cell in Packmol step (Eliseo's bug)

### ISSUE THREAD

**Issue by paulsaxe** [molssi-seamm/molsystem#16]
* molsystem version: 2020.9.30
* Python version: 3.7
* Operating System: MacOS

### Description

Running Packmol in a loop, it fails with problems setting the cell due to appending to a tuple.

### What I Did

```
Ran a flowchart with a loop over Ar and Kr with Packmol and LAMMPS
```

**Comment by seamm** [comment]
Fixed in pr#17
